# Generated by Django 4.1.1 on 2022-09-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False},
        ),
    ]
