# Generated by Django 4.1.1 on 2022-09-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0002_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
    ]
